spring:
  config:
    import: classpath:/key.yml
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${key.oauth.github.clientId}
            clientSecret: ${key.oauth.github.clientSecret}

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console.enabled: true

logging:
  level:
    root: info