spring:
  config:
    import: classpath:/key.yml
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${key.oauth.github.clientId}
            clientSecret: ${key.oauth.github.clientSecret}

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://127.0.0.1:3306/rushchat
      username: rushchat
      password: rushchat
      minimum-idle: 1
      maximum-pool-size: 5 # default 10
      idle-timeout: 10000 # default 10s
      max-lifetime: 30000 # default 30s
      connection-timeout: 5000 # default 30s

  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: chatting

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

logging:
  level:
    root: info

alarm:
  sdk:
    json:
      path: auth-rush-firebase-adminsdk-8igjb-e83e7dfc35.json